In [1]:
import pandas as pd


### `oracle_docs_raw`

Stores the **initial raw scraping results** with minimal fields (URL, title, text, word count, status, error). This is the **lightweight version** of the scraped data, useful for debugging scraping runs or quick text-only ingestion before cleaning/enrichment.

In [2]:
docs_df = pd.read_csv('oracle_docs_raw.csv')
print(len(docs_df))
docs_df.head(2)

35

,url,title,text,word_count,status,error
0,https://docs.oracle.com/en-us/iaas/Content/gen...,Overview of Generative AI Service,Overview of Generative AI Service Generative A...,1130,success,NaN
1,https://docs.oracle.com/en-us/iaas/Content/gen...,Overview of Generative AI Service,Overview of Generative AI Service Generative A...,1130,success,NaN

### `oracle_docs_structure`

Captures the **hierarchical crawl structure** of Oracle docs, with URL relationships (depth, links found, domain, path). It also includes partial metadata (title, word count, status, and text). This file is best used to **map document hierarchy** and understand the recursive crawl process.

In [3]:
docs_df = pd.read_csv('oracle_docs_structure.csv')
print(len(docs_df))
docs_df.head(2)

203

,url,title,word_count,depth,links_found,domain,path,status,text
0,https://docs.oracle.com/en-us/iaas/Content/gen...,Overview of Generative AI Service,1130,0,9,docs.oracle.com,/en-us/iaas/Content/generative-ai/overview.htm,success,Overview of Generative AI Service Generative A...
1,https://docs.oracle.com/en-us/iaas/Content/gen...,Overview of Generative AI Service,1130,0,9,docs.oracle.com,/en-us/iaas/Content/generative-ai/overview.htm,success,Overview of Generative AI Service Generative A...

### `oracle_docs_enriched`

Contains the **most complete version** of scraped Oracle documentation, including full text content, metadata (word count, character count, depth, section, path, domain), scraping status, and timestamp. This file is useful for **deep analysis and RAG ingestion**, since it provides maximum context.

In [4]:
docs_df = pd.read_csv('oracle_docs_enriched.csv')
#Drop repeated rows
docs_df = docs_df[~docs_df.apply(lambda text: (text == text.iloc[0]).all(), axis=1)]
print(len(docs_df))
docs_df.head(2)

203

,id,url,title,word_count,character_count,depth,links_found,domain,path,url_type,section,status,scraped_timestamp,text
0,1,https://docs.oracle.com/en-us/iaas/Content/gen...,Overview of Generative AI Service,1130,7103,0,9,docs.oracle.com,/en-us/iaas/Content/generative-ai/overview.htm,Overview,Overview,success,2025-07-11 21:15:39,Overview of Generative AI Service Generative A...
1,2,https://docs.oracle.com/en-us/iaas/Content/gen...,Overview of Generative AI Service,1130,7103,0,9,docs.oracle.com,/en-us/iaas/Content/generative-ai/overview.htm,Overview,Overview,success,2025-07-11 21:15:39,Overview of Generative AI Service Generative A...